### ISSUE TITLE
Minor Issue -- Atlas.dll being put in Assets/Meatkit/Managed rather than Assets/Managed

### ISSUE THREAD

**Issue by NuigoFtrdrk** [H3VR-Modding/AtlasSampleScenes#2]
With Meatkit v2 launching as official release, the Atlas UnityPackage is now a bit outdated. The user will need to move the dll manually from the original managed folder to the new one, but with no errors in the logs in regards to it, it's easy to miss the issue. The plugin being in this old folder location results in maps being unable to be built due to the "missing Atlas plugin" error.

**Comment by nrgill28** [comment]
Interesting. I tested with the OtherLoader package and Unity was smart enough to recognize the folder had moved but the Atlas package doesn't show the same behaviour. Not sure why, but I'll get a fix out for it ASAP.
